ALTER TABLE payments
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT NOW();
ALTER TABLE payments
    ADD COLUMN IF NOT EXISTS confirmed_at TIMESTAMP;
ALTER TABLE payments
    ADD COLUMN IF NOT EXISTS confirmed_by UUID REFERENCES users(id);
ALTER TABLE payments
    ADD COLUMN IF NOT EXISTS failed_at TIMESTAMP;
ALTER TABLE payments
    ADD COLUMN IF NOT EXISTS failed_by UUID REFERENCES users(id);
